### ISSUE TITLE
Clojars

### ISSUE THREAD

**Issue by nenadalm** [macchiato-framework/macchiato-migrations#1]
Hi. It looks like this library is not pushed in clojars, so it cannot be easilly installed?

**Comment by yogthos** [comment]
Hi,

I just pushed out the library to Clojars, let me know if everything is working as expected.

**Comment by nenadalm** [comment]
Thanks.

It seems it doesn't work though :)

```clojure
(migrations/migrate {:connection-string (:db-connection-string @env)})
```

```
...
TypeError: __dirname is not a function
...
app/target/out/macchiato/migrations/core.cljs:19:53
...
```

**Comment by yogthos** [comment]
Yeah that's a bug, can you try passing the `:migration-dir` explicitly to see if that works?

**Comment by nenadalm** [comment]
same issue.

**Comment by yogthos** [comment]
try with version `0.0.3`, just pushed out the fix for the path

**Comment by nenadalm** [comment]
```
TypeError: macchiato.migrations.core.node$module$postgrator.setConfig is not a function
```

Thanks, but I'll do further checks (with possible fixes) later today (or tomorrow)...

**Comment by yogthos** [comment]
Sounds good, it looks like there's a bit of work to do here still.

**Comment by yogthos** [comment]
I made a few fixes, and I'm not seeing errors locally, but I'm not seeing any migrations being run either. Not sure what I'm missing there.

**Comment by nenadalm** [comment]
thanks. Here are some fixes: https://github.com/macchiato-framework/macchiato-migrations/pull/2/files

**Comment by yogthos** [comment]
Fantastic thanks, should I push out a new version?

**Comment by nenadalm** [comment]
sure. current one is not usable :) It might take some time before I'll be able to use it though as I am using https://github.com/r0man/sqlingvo.node which is incompatible with `pg v7` (this library doesn't work with `pg v5`).

**Comment by yogthos** [comment]
Ah sounds good, and pushed out a new version. Good eye on the `async`. :)
